# Generated by Django 4.1.7 on 2023-03-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0002_order_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('1', 'CASH'), ('2', 'Credit Card')], default='1', max_length=1),
        ),
    ]
